let data=[];const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const wikiCache={};
async function wikiImage(q){if(wikiCache[q])return wikiCache[q];try{const r=await fetch(`https://es.wikipedia.org/api/rest_v1/page/summary/${encodeURIComponent(q)}`);if(!r.ok)throw Error();const d=await r.json();wikiCache[q]={img:d.thumbnail?.source||'',title:d.title||q,url:d.content_urls?.desktop?.page||''};return wikiCache[q]}catch(e){return {img:'',title:q,url:''}}}
async function init(){try{data=await fetch('data.json').then(r=>r.json())}catch(e){data=[]}const f=$('#periodFilter');[...new Set(data.map(x=>x.periodo))].forEach(p=>f.insertAdjacentHTML('beforeend',`<option value="${esc(p)}">${esc(p)}</option>`));render();loadHero();}
async function loadHero(){const x=await wikiImage('Theatre of Dionysus');if(x.img)$('#heroImage').src=x.img}
function getItems(){const q=$('#search').value.trim().toLowerCase(),f=$('#periodFilter').value;return data.filter(x=>(f==='all'||x.periodo===f)&&(!q||JSON.stringify(x).toLowerCase().includes(q)))}
function render(){const items=getItems(),list=$('#cards');$('#empty').hidden=items.length!==0;list.innerHTML=items.map((x,i)=>{const n=data.indexOf(x);return `<article class="timeline-item"><div class="timeline-index">${String(n+1).padStart(2,'0')}</div><div class="card" tabindex="0" role="button" onclick="openItem(${n})" onkeydown="if(event.key==='Enter'||event.key===' ')openItem(${n})"><div class="card-image"><img loading="lazy" src="${esc(x.image||'')}" data-wiki="${esc(x.apiQuery)}" alt="Ilustración: ${esc(x.titulo)}"><span>${esc(x.periodo)}</span></div><div class="card-body"><div class="card-top"><span class="period">${esc(x.fecha)}</span><span class="card-arrow">↗</span></div><h3>${esc(x.titulo)}</h3><p>${esc(x.resumen)}</p><div class="chips">${(x.apunte||[]).slice(0,5).map(t=>`<span class="chip note-chip">${esc(t)}</span>`).join('')}</div></div></div></article>`}).join('');drawMarkers(items);loadCardImages()}
async function loadCardImages(){const imgs=[...document.querySelectorAll('.card-image img[data-wiki]')];await Promise.all(imgs.map(async img=>{if(img.src){}const q=img.dataset.wiki;const x=await wikiImage(q);if(x.img)img.src=x.img;else img.src='https://commons.wikimedia.org/wiki/Special:FilePath/Theatre%20in%20shakespeares%20time%20interior%20view.png'}))}
function drawMarkers(items){const m=$('#markers');m.innerHTML=items.map((x,i)=>`<button class="marker" style="top:${i*318+155}px" title="${esc(x.titulo)}" aria-label="${esc(x.titulo)}" onclick="openItem(${data.indexOf(x)})"></button>`).join('');updateProgress()}
function updateProgress(){const shell=document.querySelector('.timeline-shell'),p=$('#trackProgress');if(!shell)return;const r=shell.getBoundingClientRect(),seen=Math.max(0,Math.min(shell.offsetHeight,innerHeight-r.top));p.style.height=`${Math.min(100,seen/Math.max(shell.offsetHeight,1)*100)}%`}
async function openItem(i){const x=data[i];if(!x)return;const w=await wikiImage(x.apiQuery);$('#modalContent').innerHTML=`<div class="modal-hero">${w.img?`<img src="${esc(w.img)}" alt="${esc(x.titulo)}">`:''}<div><div class="modal-date">${esc(x.periodo)} · ${esc(x.fecha)}</div><h2>${esc(x.titulo)}</h2><p class="lead">${esc(x.resumen)}</p></div></div><div class="detail-grid"><div><h4>CONTENIDO DE LA PPT</h4><ul>${(x.puntos||[]).map(v=>`<li>${esc(v)}</li>`).join('')}</ul></div><div><h4>PERSONAJES Y OBRAS</h4><p>${[...(x.personajes||[]),...(x.obras||[])].map(v=>`<span class="chip">${esc(v)}</span> `).join('')||'No especificados en esta etapa.'}</p></div></div><div class="note-box"><strong>APUNTE DE CLASE ASOCIADO</strong><p>${(x.apunte||[]).map(esc).join(' · ')||'Sin anotación registrada.'}</p></div><button class="api-btn" onclick="apiContext(${i})">Consultar contexto dinámico ↗</button><div id="apiResult" class="api-result" hidden></div><p class="source-line">${esc(x.fuente)}${w.url?` · <a target="_blank" rel="noopener" href="${esc(w.url)}">Ver referencia visual ↗</a>`:''}</p>`;$('#modal').classList.add('open');$('#modal').setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}
async function apiContext(i){const out=$('#apiResult');out.hidden=false;out.textContent='Consultando contexto dinámico…';try{const x=data[i],r=await fetch(`https://es.wikipedia.org/api/rest_v1/page/summary/${encodeURIComponent(x.apiQuery)}`);if(!r.ok)throw Error();const d=await r.json();out.innerHTML=`<strong>${esc(d.title||'Contexto')}</strong><p>${esc(d.extract||'Sin resumen disponible.')}</p>${d.content_urls?.desktop?.page?`<a target="_blank" rel="noopener" href="${esc(d.content_urls.desktop.page)}">Abrir referencia externa ↗</a>`:''}`}catch(e){out.textContent='No fue posible consultar la API en este momento. El contenido académico local continúa disponible.'}}
function closeModal(){$('#modal').classList.remove('open');$('#modal').setAttribute('aria-hidden','true');document.body.style.overflow=''}
$('#search').addEventListener('input',render);$('#periodFilter').addEventListener('change',render);$('#clearBtn').addEventListener('click',()=>{$('#search').value='';$('#periodFilter').value='all';render()});$('#close').addEventListener('click',closeModal);$('#modal').addEventListener('click',e=>{if(e.target.id==='modal')closeModal()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});addEventListener('scroll',()=>{updateProgress();[...document.querySelectorAll('.marker')].forEach(m=>{const r=m.getBoundingClientRect();m.classList.toggle('active',r.top>80&&r.top<innerHeight*.62)})},{passive:true});$('#startBtn').addEventListener('click',()=>document.querySelector('#linea').scrollIntoView({behavior:'smooth'}));$('#themeBtn').addEventListener('click',()=>document.body.classList.toggle('light'));init();
